require('dotenv').config();
require('./config/database');

const Category = require('./models/category');
const Player = require('./models/player');


(async function() {
  await Category.deleteMany({});
  const categories = await Category.create([
    {name: 'Quarterbacks', sortOrder: 10},
    {name: 'Running Backs', sortOrder: 20},
    {name: 'Wide Receivers', sortOrder: 30},
    {name: 'Tight Ends', sortOrder: 40},
    {name: 'Kickers', sortOrder: 50},
    {name: 'Team Defenses', sortOrder: 60},
  ]);

  await Player.deleteMany({});
  const players = await Player.create([
    {name: '(QB)Patrick Mahomes(KC)', category: categories[0], tier: 1},
    {name: '(QB)Jalen Hurts(PHI)', category: categories[0], tier: 1},
    {name: '(QB)Josh Allen(BUF)', category: categories[0], tier: 1},
    {name: '(QB)Lamar Jackson(BAL)', category: categories[0], tier: 2},
    {name: '(QB)Joe Burrow(CIN)', category: categories[0], tier: 2},
    {name: '(QB)Justin Fields(CHI)', category: categories[0], tier: 2},
    {name: '(QB)Justin Herbert(LAC)', category: categories[0], tier: 2},
    {name: '(QB)Trevor Lawrence(JAC)', category: categories[0], tier: 2},
    {name: '(QB)Deshaun Watson(CLE)', category: categories[0], tier: 3},
    {name: '(QB)Daniel Jones(NYG)', category: categories[0], tier: 3},
    {name: '(QB)Dak Prescott(DAL)', category: categories[0], tier: 3},
    {name: '(QB)Tua Tagovailoa(MIA)', category: categories[0], tier: 3},
    {name: '(QB)Geno Smith(SEA)', category: categories[0], tier: 3},
    {name: '(QB)Kirk Cousins(MIN)', category: categories[0], tier: 3},
    {name: '(QB)Anthony Richardson(IND)', category: categories[0], tier: 3},
    {name: '(QB)Aaron Rodgers(GB)', category: categories[0], tier: 3},
    {name: '(QB)Jared Goff(DET)', category: categories[0], tier: 4},
    {name: '(QB)Russell Wilson(DEN)', category: categories[0], tier: 4},
    {name: '(QB)Derek Carr(NO)', category: categories[0], tier: 4},
    {name: '(QB)Kenny Pickett(PIT)', category: categories[0], tier: 4},
    {name: '(QB)Jordan Love(GB)', category: categories[0], tier: 4},
    {name: '(QB)Matthew Stafford(LAR)', category: categories[0], tier: 4},
    {name: '(QB)Brock Purdy(SF)', category: categories[0], tier: 4},
    {name: '(QB)Sam Howell(WAS)', category: categories[0], tier: 4},
    {name: '(QB)Bryce Young(CAR)', category: categories[0], tier: 4},
    {name: '(QB)Ryan Tannehill(TEN)', category: categories[0], tier: 4},
    {name: '(QB)Jimmy Garrapolo(LV)', category: categories[0], tier: 4},
    {name: '(QB)Mac Jones(NE)', category: categories[0], tier: 4},
    {name: '(QB)CJ Stroud(HOU)', category: categories[0], tier: 4},
    {name: '(RB)Christain MaCaffrey(SF)', category: categories[1], tier: 1},
    {name: '(RB)Nick Chubb(CLE)', category: categories[1], tier: 1},
    {name: '(RB)Austin Ekeler(LAC)', category: categories[1], tier: 1},
    {name: '(RB)Bijan Robinson(ATL)', category: categories[1], tier: 1},
    {name: '(RB)Derrick Henry(TEN)', category: categories[1], tier: 2},
    {name: '(RB)Tony Pollard(DAL)', category: categories[1], tier: 2},
    {name: '(RB)Saquon Barkley(NYG)', category: categories[1], tier: 2},
    {name: '(RB)Josh Jacobs(LV)', category: categories[1], tier: 2},
    {name: '(RB)Joe Mixon(CIN)', category: categories[1], tier: 3},
    {name: '(RB)Najee Harris(PIT)', category: categories[1], tier: 3},
    {name: '(RB)Rhamondre Stevenson(NE)', category: categories[1], tier: 3},
    {name: '(RB)Travis Etienne Jr.(JAC)', category: categories[1], tier: 3},
    {name: '(RB)Jahmyr Gibbs(DET)', category: categories[1], tier: 3},
    {name: '(RB)Aaron Jones(GB)', category: categories[1], tier: 3},
    {name: '(RB)Kenneth Walker(SEA)', category: categories[1], tier: 3},
    {name: '(RB)Dameon Pierce(HOU)', category: categories[1], tier: 4},
    {name: '(RB)J.K. Dobbins(BAL)', category: categories[1], tier: 4},
    {name: '(RB)Miles Sanders(CAR)', category: categories[1], tier: 4},
    {name: '(RB)Breece Hall(NYJ)', category: categories[1], tier: 4},
    {name: '(RB)Alexander Mattison(MIN)', category: categories[1], tier: 4},
    {name: '(RB)Cam Akers(LAR)', category: categories[1], tier: 4},
    {name: '(RB)James Connor(AZ)', category: categories[1], tier: 4},
    {name: '(RB)David Montgomery(DET)', category: categories[1], tier: 4},
    {name: '(RB)James Cook(BUF)', category: categories[1], tier: 4},
    {name: '(RB)Jonathan Taylor(IND)', category: categories[1], tier: 4},
    {name: '(RB)Rachaad White(TB)', category: categories[1], tier: 4},
    {name: '(RB)Javonte Williams(DEN)', category: categories[1], tier: 4},
    {name: '(RB)Isiah Pacheco(KC)', category: categories[1], tier: 4},
    {name: '(RB)Alvin Kamara(NO)', category: categories[1], tier: 5},
    {name: '(RB)Dalvin Cook(NYJ)', category: categories[1], tier: 5},
    {name: '(RB)Khalil Herbert(CHI)', category: categories[1], tier: 5},
    {name: '(RB)Deandre Swift(PHI)', category: categories[1], tier: 5},
    {name: '(RB)Brian Robinson(WAS)', category: categories[1], tier: 5},
    {name: '(RB)AJ Dillon(GB)', category: categories[1], tier: 5},
    {name: '(RB)Antonio Gibson(WAS)', category: categories[1], tier: 5},
    {name: '(RB)Samaje Perine(DEN)', category: categories[1], tier: 5},
    {name: '(RB)Jamaal Williams(NO)', category: categories[1], tier: 5},
    {name: '(RB)Zach Charbonnet(SEA)', category: categories[1], tier: 5},
    {name: '(RB)Rashaad Penny(PHI)', category: categories[1], tier: 5},
    {name: '(RB)Raheem Mostert(MIA)', category: categories[1], tier: 6},
    {name: '(RB)Elijah Mitchell(SF)', category: categories[1], tier: 6},
    {name: '(RB)Damien Harris(BUF)', category: categories[1], tier: 6},
    {name: '(RB)Tyler Allgeier(ATL)', category: categories[1], tier: 6},
    {name: '(RB)Jaylen Warren(PIT)', category: categories[1], tier: 6},
    {name: '(RB)Ezekiel Elliott(NE)', category: categories[1], tier: 6},
    {name: '(RB)Devin Singletary(HOU)', category: categories[1], tier: 6},
    {name: '(WR)Justin Jefferson(MIN)', category: categories[2], tier: 1},
    {name: '(WR)JaMaar Chase(CIN)', category: categories[2], tier: 1},
    {name: '(WR)Tyreek Hill(MIA)', category: categories[2], tier: 1},
    {name: '(WR)Stefon Diggs(BUF)', category: categories[2], tier: 2},
    {name: '(WR)A.J. Brown(PHI)', category: categories[2], tier: 2},
    {name: '(WR)CeDee Lamb(DAL)', category: categories[2], tier: 2},
    {name: '(WR)Davante Adams(LV)', category: categories[2], tier: 2},
    {name: '(WR)Amon-Ra St.Brown(DET)', category: categories[2], tier: 2},
    {name: '(WR)Coopoer Kupp(LAR)', category: categories[2], tier: 2},
    {name: '(WR)Garrett Wilson(NYJ)', category: categories[2], tier: 2},
    {name: '(WR)Jaylen Waddle(MIA)', category: categories[2], tier: 3},
    {name: '(WR)Chris Olave(NO)', category: categories[2], tier: 3},
    {name: '(WR)Tee Higgins(CIN)', category: categories[2], tier: 3},
    {name: '(WR)DeVonta Smith(PHI)', category: categories[2], tier: 3},
    {name: '(WR)Amari Cooper(CLE)', category: categories[2], tier: 3},
    {name: '(WR)Deebo Samuel(SF)', category: categories[2], tier: 3},
    {name: '(WR)DK Metcalf(SEA)', category: categories[2], tier: 4},
    {name: '(WR)Calvin Ridley(ATL)', category: categories[2], tier: 4},
    {name: '(WR)DJ Moore(CHI)', category: categories[2], tier: 4},
    {name: '(WR)Christain Watson(GB)', category: categories[2], tier: 4},
    {name: '(WR)Keenan Allen(LAC)', category: categories[2], tier: 4},
    {name: '(WR)Brandon Aiyuk(SF)', category: categories[2], tier: 4},
    {name: '(WR)DeAndre Hopkins(TEN)', category: categories[2], tier: 4},
    {name: '(WR)Terry McLaurin(WAS)', category: categories[2], tier: 4},
    {name: '(WR)Drake London(ATL)', category: categories[2], tier: 5},
    {name: '(WR)Mike Williams(LAC)', category: categories[2], tier: 5},
    {name: '(WR)Tyler Lockett(SEA)', category: categories[2], tier: 5},
    {name: '(WR)Mike Evans(TB)', category: categories[2], tier: 5},
    {name: '(WR)Christain Kirk(JAC)', category: categories[2], tier: 5},
    {name: '(WR)Jahan Dotson(WAS)', category: categories[2], tier: 5},
    {name: '(WR)Dionte Johnson(PIT)', category: categories[2], tier: 5},
    {name: '(WR)Chris Godwin(TB)', category: categories[2], tier: 5},
    {name: '(WR)George Pickens(PIT)', category: categories[2], tier: 5},
    {name: '(WR)Jerry Jeudy(DEN))', category: categories[2], tier: 5},
    {name: '(WR)Gabe Davis(BUF)', category: categories[2], tier: 5},
    {name: '(WR)Marquise Brown(ARI)', category: categories[2], tier: 5},
    {name: '(WR)Michael Pittman(IND)', category: categories[2], tier: 5},
    {name: '(WR)Jordan Addison(MIN)', category: categories[2], tier: 5},
    {name: '(WR)Courland Sutton(DEN)', category: categories[2], tier: 6},
    {name: '(WR)Brandin Cooks(DAL)', category: categories[2], tier: 6},
    {name: '(WR)Jaxon Smith-Nigba(SEA)', category: categories[2], tier: 6},
    {name: '(WR)Zay Flowers(BAL)', category: categories[2], tier: 6},
    {name: '(WR)Treylon Burks(TEN)', category: categories[2], tier: 6},
    {name: '(WR)Elijah Moore(CLE)', category: categories[2], tier: 6},
    {name: '(WR)Rashod Bateman(BAL)', category: categories[2], tier: 6},
    {name: '(WR)Skyy Moore(KC)', category: categories[2], tier: 6},
    {name: '(WR)Quentin Johnston(LAC)', category: categories[2], tier: 6},
    {name: '(WR)Michael Thomas(NO)', category: categories[2], tier: 6},
    {name: '(WR)Kadarius Toney(KC)', category: categories[2], tier: 6},
    {name: '(WR)Allen Lazard(NYJ)', category: categories[2], tier: 6},
    {name: '(TE)Travis Kelce(KC)', category: categories[3], tier: 1},
    {name: '(TE)Mark Andrews(BAL)', category: categories[3], tier: 1},
    {name: '(TE)T.J. Hockenson(MIN)', category: categories[3], tier: 1},
    {name: '(TE)Darren Waller(NYG)', category: categories[3], tier: 2},
    {name: '(TE)George Kittle(SF)', category: categories[3], tier: 2},
    {name: '(TE)Kyle Pitts(ATL)', category: categories[3], tier: 2},
    {name: '(TE)Dallas Goedert(PHI)', category: categories[3], tier: 2},
    {name: '(TE)Pat Freiermuth(PIT)', category: categories[3], tier: 2},
    {name: '(TE)Evan Engram(JAC)', category: categories[3], tier: 2},
    {name: '(TE)David Njoku(CLE)', category: categories[3], tier: 3},
    {name: '(TE)Chigoziem Okonkwo(TEN)', category: categories[3], tier: 3},
    {name: '(TE)Dalton Schultz(HOU)', category: categories[3], tier: 3},
    {name: '(TE)Dalton Kincaid(BUF)', category: categories[3], tier: 3},
    {name: '(TE)Tyler Higbee(LAR)', category: categories[3], tier: 3},
    {name: '(TE)Cole Kmet(CHI)', category: categories[3], tier: 3},
    {name: '(TE)Greg Dulcich(DEN)', category: categories[3], tier: 3},
    {name: '(TE)Juwan Johnson(NO)', category: categories[3], tier: 3},
    {name: '(TE)Gerald Everett(LAC)', category: categories[3], tier: 3},
    {name: '(TE)Sam LaPorta(DET)', category: categories[3], tier: 4},
    {name: '(TE)Irv Smith Jr.(CIN)', category: categories[3], tier: 4},
    {name: '(TE)Taysom Hill(NO)', category: categories[3], tier: 4},
    {name: '(TE)Hunter Henry(NE)', category: categories[3], tier: 4},
    {name: '(TE)Dawson Knox(BUF)', category: categories[3], tier: 4},
    {name: '(TE)Hayden Hurt(CAR)', category: categories[3], tier: 4},
    {name: '(K)Justin Tucker(BAL)', category: categories[4], tier: 1},
    {name: '(K)Tyler Bass(BUF)', category: categories[4], tier: 1},
    {name: '(K)Harrison Butker(KC)', category: categories[4], tier: 1},
    {name: '(K)Evan McPherson(CIN)', category: categories[4], tier: 1},
    {name: '(K)Daniel Carlson(LV)', category: categories[4], tier: 2},
    {name: '(K)Younghoe Koo(ATL)', category: categories[4], tier: 2},
    {name: '(K)Jaon Sanders(MIA)', category: categories[4], tier: 2},
    {name: '(K)Jason Myers(SEA)', category: categories[4], tier: 2},
    {name: '(K)Jake Elliott(PHI)', category: categories[4], tier: 2},
    {name: '(K)Brandon McManus(JAC)', category: categories[4], tier: 3},
    {name: '(K)Greg Zurlein(NYJ)', category: categories[4], tier: 3},
    {name: '(K)Greg Joseph(MIN)', category: categories[4], tier: 3},
    {name: '(K)Graham Gano(NYG)', category: categories[4], tier: 3},
    {name: '(K)Will Lutz(DEN)', category: categories[4], tier: 3},
    {name: '(K)Jake Moody(SF)', category: categories[4], tier: 3},
    {name: 'San Francisco 49ers', category: categories[5], tier: 1},
    {name: 'Dallas Cowboys', category: categories[5], tier: 1},
    {name: 'Philadelphia Eagles', category: categories[5], tier: 1},
    {name: 'Buffalo Bills', category: categories[5], tier: 2},
    {name: 'New York Jets', category: categories[5], tier: 2},
    {name: 'New England Patriots', category: categories[5], tier: 2},
    {name: 'Baltimore Ravens', category: categories[5], tier: 2},
    {name: 'Pittsburgh Steelers', category: categories[5], tier: 3},
    {name: 'Denver Broncos', category: categories[5], tier: 3},
    {name: 'Kansas City Chiefs', category: categories[5], tier: 3},
    {name: 'New Orleans Saints', category: categories[5], tier: 3},
    {name: 'Miami Dolphins', category: categories[5], tier: 3},
    {name: 'Washington Commanders', category: categories[5], tier: 3},
    {name: 'Cincinnati Bengals', category: categories[5], tier: 4},
    {name: 'Cleveland Browns', category: categories[5], tier: 4},
    {name: 'Green Bay Packers', category: categories[5], tier: 4},
    {name: 'Los Angeles Chargers', category: categories[5], tier: 4},
    {name: 'Jacksonville Jaguars', category: categories[5], tier: 4},
    {name: 'Tampa Bay Buccaneers', category: categories[5], tier: 4},
    {name: 'Seattle Seahawks', category: categories[5], tier: 4},
    {name: 'Indianapolis Colts', category: categories[5], tier: 4},
    {name: 'Carolina Panthers', category: categories[5], tier: 4},
    {name: 'Tennessee Titans', category: categories[5], tier: 4},
    {name: 'New York Giants', category: categories[5], tier: 4},
    {name: 'Detroit Lions', category: categories[5], tier: 4},
    {name: 'Los Angeles Rams', category: categories[5], tier: 4},
    {name: 'Minnesota Vikings', category: categories[5], tier: 4},
    {name: 'Atlanta Falcons', category: categories[5], tier: 4},
    {name: 'Arizona Cardinals', category: categories[5], tier: 4},
    {name: 'Houston Texans', category: categories[5], tier: 4},
    {name: 'Chicago Bears', category: categories[5], tier: 4},
    {name: 'Las Vegas Raiders', category: categories[5], tier: 4},
  ]);

  console.log(players)

  process.exit();

})();
